DROP FUNCTION IF EXISTS utc_age(param_date DATE) CASCADE;
DROP SEQUENCE IF EXISTS imports_serial CASCADE;
DROP TYPE IF EXISTS gender CASCADE;
DROP TYPE IF EXISTS citizen_fields CASCADE;
DROP TABLE IF EXISTS Imports CASCADE;
DROP TABLE IF EXISTS Citizens CASCADE;
DROP TABLE IF EXISTS Relatives CASCADE;
